[package]
name = "rosfix"
version = "0.1.2"
edition = "2021"
rust-version = "1.75"
readme = "../../README.md"
description = "High-Performance Multi-Language Static Verification and Active Remediation Engine for ROS 2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SohamWalam11/ros2-safety-lint"
homepage = "https://github.com/SohamWalam11/ros2-safety-lint"
documentation = "https://docs.rs/rosfix"
keywords = ["ros2", "robotics", "security", "linter", "static-analysis"]
categories = ["development-tools::testing", "command-line-utilities"]

[[bin]]
name = "rosfix"
path = "src/main.rs"

[[bin]]
name = "cargo-rosfix"
path = "src/main.rs"

[dependencies]
roxmltree = "0.20"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
rustpython-parser = "0.4.0"
regex = "1.13.1"
tree-sitter = "0.20"
tree-sitter-cpp = "0.20"
toml = "0.8"
walkdir = "2.5.0"
miette = { version = "7.6.0", features = ["fancy"] }
rayon = "1.10"
